version: "3.7"

services:
  redis_ui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - 7843:7843
    volumes:
      - ./redis:/settings
    networks:
      - internal

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - internal


networks:
  internal:
    external: false