cache:
  RedisURL: "redis://host:port/db"

db:
  DataBaseURL: "postgres://u:p@host:5432/db"

server:
  Port: 34567
  ReadTimeout: 60
  AppName: "MyApp"
  ServerHeader: "MyApp"
  Prefork: true


logger:
  LogFile: "/tmp/myapp.log"
  Timezone: "Africa/Nairobi"
  LoggerMaxFileSize: 10
  CompressLogFile: true
  UseLocalTime: true